FROM oven/bun:1

WORKDIR /src/worker

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/worker ./apps/worker

RUN bun install

CMD ["bun", "run", "dev"]