FROM oven/bun:1

WORKDIR /src/web

COPY ./packages ./packages
COPY ./bun.lock  ./bun.lock

COPY ./packages.json  ./packages.json
COPY ./turbo.json  ./turbo.json

COPY ./apps/web2 ./apps/web2

RUN bun install 

RUN bun run build

EXPOSE 3000

CMD ["bun" , "run" , "start:frontend"]