FROM oven/bun:1

WORKDIR /src/producer

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/producer ./apps/producer

RUN bun run dev

CMD ["bun" ,"run" , "dev"]

