FROM bun/over:1

WORKDIR  ./src/api

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./packages.json ./packages.json
COPY ./turbo.json  ./turbo.json 

RUN bun install 

RUN bun run db:generate

EXPOSE 4000

CMD [ "bun" , "run" , "start:backend:migratefirst"]